### PR TITLE
fix(cpp/go):  invalid variable names of getters

### LINKED ISSUE #47: cpp/go: need more support for Tableau yaml
My yaml metasheet is discribed as follows:
image
Generated proto is as follows:
image
Generated getters are as follows in cpp code:
image
Generated getters are as follows in go code:
image

Expected getters should be:
* If `@key` is not assigned in metasheet, params should be `key1` `key2` `key3`.
* If `@key` is assigned in metasheet, params should be the names assigned, which are `obj_type` `type` `id` in this case.

### PR DESCRIPTION
**Pull request by Kybxd**
- close #47
Generated getters when custom names are used for yaml keys:
image
image
image

Generated getters when no custom name is used for yaml keys:
image
image
image

### CODE REVIEW

File: cmd/protoc-gen-cpp-tableau-loader/helper/keyword.go [hunk 1]
```diff
@@ -1,8 +1,28 @@
...
+	"unicode"
+
+	"github.com/elliotchance/pie/v2"
+)
+
 var cppKeywords map[string]bool
 
-func KeywordEscape(str string) string {
+func VarNameEscape(str string) string {
+	// Filter invalid runes
```
Comment (wenchy) [inline cmd/protoc-gen-cpp-tableau-loader/helper/keyword.go:12]: - this is a small plugin, DO NOT import big package "github.com/elliotchance/pie/v2" for only one feature
- rename `VarNameEscape` -> `escapeIdentifier`, refer: https://en.cppreference.com/w/cpp/language/identifiers
```
package main

import (
	"fmt"
	"strings"
	"unicode"
)

func removeNonAlnum(s string) string {
	var result strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsNumber(r) || r == '_' {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func main() {
	str := "Hello, World!_123"
	fmt.Println(removeNonAlnum(str)) // Prints: HelloWorld_123
}
```

**Review by wenchy — CHANGES_REQUESTED** [review]

File: cmd/protoc-gen-cpp-tableau-loader/helper/keyword.go (hunk 1 above)
Comment (Kybxd) [reply cmd/protoc-gen-cpp-tableau-loader/helper/keyword.go]: done

File: cmd/protoc-gen-cpp-tableau-loader/helper/helper.go [hunk 2]
```diff
@@ -102,7 +102,8 @@ func AddMapKey(fd protoreflect.FieldDescriptor, keys []MapKey) []MapKey {
 	opts := fd.Options().(*descriptorpb.FieldOptions)
 	fdOpts := proto.GetExtension(opts, tableaupb.E_Field).(*tableaupb.FieldOptions)
 	name := strcase.ToSnake(strings.TrimSpace(fdOpts.GetKey()))
-	if name == "" {
+	name = escapeIdentifier(name)
+	if name == "" || name == "key" {
```
Comment (wenchy) [inline cmd/protoc-gen-cpp-tableau-loader/helper/helper.go:106]: find the protobuf map key field name in map value message

https://github.com/tableauio/loader/blob/9567d70a3080e6c831e9a15db752e37f18ab8ff9/cmd/protoc-gen-go-tableau-loader/check/check.go#L37-L45

**Review by wenchy — CHANGES_REQUESTED** [review]

**Review by wenchy — APPROVED** [review]
