### PR TITLE
fix: make std::string const ref in cpp function param

### LINKED ISSUE #29: load(cpp): function param is not const ref when using string as index
企业微信截图_16844879062652

image

image

### PR DESCRIPTION
**Pull request by Kybxd**
* close #29

### CODE REVIEW

File: cmd/protoc-gen-cpp-tableau-loader/helper/helper.go [hunk 1]
```diff
@@ -81,6 +81,13 @@ func ParseCppType(fd protoreflect.FieldDescriptor) string {
 	}
 }
 
+func ConvertCppTypeToConstRef(cpptype string) string {
```
Comment (wenchy) [inline cmd/protoc-gen-cpp-tableau-loader/helper/helper.go:84]: rename func name to `ToConstRefType`

Comment (Kybxd) [reply cmd/protoc-gen-cpp-tableau-loader/helper/helper.go]: done

**Review by wenchy — APPROVED** [review]
LGTM
